//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenData.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class XT_AnimalMedicine
    {
        public int PK { get; set; }
        public string LicenseNum { get; set; }
        public string ChName { get; set; }
        public string EnName { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string FactoryName { get; set; }
        public string FactoryAddress { get; set; }
        public string DosageForm { get; set; }
        public string Package { get; set; }
        public string Indications { get; set; }
        public string Element { get; set; }
        public string IssueDate { get; set; }
        public string ValidPeriod { get; set; }
        public bool ForExport { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EditUser { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
